# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\PycharmProjects\Sadna\GUI\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from constants import Tasks

class Ui_MainView(object):
    def setupUi(self, MainView):
        MainView.setObjectName("MainView")
        MainView.resize(425, 585)
        self.centralwidget = QtWidgets.QWidget(MainView)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.predictView = QtWidgets.QWidget()
        self.predictView.setObjectName("predictView")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.predictView)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.inputFilesLineEdit = QtWidgets.QLineEdit(self.predictView)
        self.inputFilesLineEdit.setObjectName("inputFilesLineEdit")
        self.gridLayout_4.addWidget(self.inputFilesLineEdit, 1, 0, 1, 1)
        self.selectInputFilesLabel = QtWidgets.QLabel(self.predictView)
        self.selectInputFilesLabel.setObjectName("selectInputFilesLabel")
        self.gridLayout_4.addWidget(self.selectInputFilesLabel, 0, 0, 1, 1)
        self.selectOutputDirLabel = QtWidgets.QLabel(self.predictView)
        self.selectOutputDirLabel.setObjectName("selectOutputDirLabel")
        self.gridLayout_4.addWidget(self.selectOutputDirLabel, 2, 0, 1, 1)
        self.browseInputFilesButton = QtWidgets.QPushButton(self.predictView)
        self.browseInputFilesButton.setObjectName("browseInputFilesButton")
        self.gridLayout_4.addWidget(self.browseInputFilesButton, 1, 1, 1, 1)
        self.browseOutputDirButton = QtWidgets.QPushButton(self.predictView)
        self.browseOutputDirButton.setObjectName("browseOutputDirButton")
        self.gridLayout_4.addWidget(self.browseOutputDirButton, 3, 1, 1, 1)
        self.selectTasksLabel = QtWidgets.QLabel(self.predictView)
        self.selectTasksLabel.setObjectName("selectTasksLabel")
        self.gridLayout_4.addWidget(self.selectTasksLabel, 4, 0, 1, 1)
        self.outputDirLineEdit = QtWidgets.QLineEdit(self.predictView)
        self.outputDirLineEdit.setObjectName("outputDirLineEdit")
        self.gridLayout_4.addWidget(self.outputDirLineEdit, 3, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.runPredictButton = QtWidgets.QPushButton(self.predictView)
        self.runPredictButton.setObjectName("runPredictButton")
        self.gridLayout_6.addWidget(self.runPredictButton, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.tasksTree = QtWidgets.QTreeWidget(self.predictView)
        self.tasksTree.setObjectName("tasksTree")
        self.gridLayout_6.addWidget(self.tasksTree, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 5, 0, 1, 1)
        self.tabWidget.addTab(self.predictView, "")
        self.AnalyzeView = QtWidgets.QWidget()
        self.AnalyzeView.setObjectName("AnalyzeView")
        self.gridLayout = QtWidgets.QGridLayout(self.AnalyzeView)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.predictedInputBrowseButton = QtWidgets.QPushButton(self.AnalyzeView)
        self.predictedInputBrowseButton.setObjectName("predictedInputBrowseButton")
        self.gridLayout.addWidget(self.predictedInputBrowseButton, 4, 2, 1, 1)
        self.predictedInputLabel = QtWidgets.QLabel(self.AnalyzeView)
        self.predictedInputLabel.setObjectName("predictedInputLabel")
        self.gridLayout.addWidget(self.predictedInputLabel, 3, 0, 1, 1)
        self.analysisCorrelationsRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.analysisCorrelationsRadioButton.setObjectName("analysisCorrelationsRadioButton")
        self.gridLayout.addWidget(self.analysisCorrelationsRadioButton, 6, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 19, 0, 1, 1)
        self.runAnalysisButton = QtWidgets.QPushButton(self.AnalyzeView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runAnalysisButton.sizePolicy().hasHeightForWidth())
        self.runAnalysisButton.setSizePolicy(sizePolicy)
        self.runAnalysisButton.setObjectName("runAnalysisButton")
        self.gridLayout.addWidget(self.runAnalysisButton, 8, 0, 1, 1)
        self.analysisSignificantRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.analysisSignificantRadioButton.setObjectName("analysisSignificantRadioButton")
        self.gridLayout.addWidget(self.analysisSignificantRadioButton, 7, 0, 1, 1)
        self.analysisNameLineEdit = QtWidgets.QLineEdit(self.AnalyzeView)
        self.analysisNameLineEdit.setObjectName("analysisNameLineEdit")
        self.gridLayout.addWidget(self.analysisNameLineEdit, 1, 0, 1, 1)
        self.analysisNameLabel = QtWidgets.QLabel(self.AnalyzeView)
        self.analysisNameLabel.setObjectName("analysisNameLabel")
        self.gridLayout.addWidget(self.analysisNameLabel, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.AnalyzeView)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 13, 0, 1, 3)
        self.actualInputBrowseButton = QtWidgets.QPushButton(self.AnalyzeView)
        self.actualInputBrowseButton.setObjectName("actualInputBrowseButton")
        self.gridLayout.addWidget(self.actualInputBrowseButton, 15, 2, 1, 1)
        self.predictedInputLineEdit = QtWidgets.QLineEdit(self.AnalyzeView)
        self.predictedInputLineEdit.setObjectName("predictedInputLineEdit")
        self.gridLayout.addWidget(self.predictedInputLineEdit, 4, 0, 1, 2)
        self.actualInputLineEdit = QtWidgets.QLineEdit(self.AnalyzeView)
        self.actualInputLineEdit.setObjectName("actualInputLineEdit")
        self.gridLayout.addWidget(self.actualInputLineEdit, 15, 0, 1, 2)
        self.actualInputLabel = QtWidgets.QLabel(self.AnalyzeView)
        self.actualInputLabel.setObjectName("actualInputLabel")
        self.gridLayout.addWidget(self.actualInputLabel, 14, 0, 1, 1)
        self.analysisMeanRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.analysisMeanRadioButton.setObjectName("analysisMeanRadioButton")
        self.gridLayout.addWidget(self.analysisMeanRadioButton, 5, 0, 1, 1)
        self.comparisonSignificantRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.comparisonSignificantRadioButton.setObjectName("comparisonSignificantRadioButton")
        self.gridLayout.addWidget(self.comparisonSignificantRadioButton, 17, 0, 1, 1)
        self.comparisonCorrelationsRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.comparisonCorrelationsRadioButton.setObjectName("comparisonCorrelationsRadioButton")
        self.gridLayout.addWidget(self.comparisonCorrelationsRadioButton, 16, 0, 1, 1)
        self.runComparisonButton = QtWidgets.QPushButton(self.AnalyzeView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runComparisonButton.sizePolicy().hasHeightForWidth())
        self.runComparisonButton.setSizePolicy(sizePolicy)
        self.runComparisonButton.setObjectName("runComparisonButton")
        self.gridLayout.addWidget(self.runComparisonButton, 18, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 9, 0, 1, 1)
        self.tabWidget.addTab(self.AnalyzeView, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainView.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainView)
        self.statusbar.setObjectName("statusbar")
        MainView.setStatusBar(self.statusbar)

        self.retranslateUi(MainView)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainView)

    def retranslateUi(self, MainView):
        _translate = QtCore.QCoreApplication.translate
        ### code added manually ###
        self.tasksTree.headerItem().setText(0, _translate("MainView", "Tasks"))
        for task in Tasks:
            taskItem = QtWidgets.QTreeWidgetItem(self.tasksTree)
            taskItem.setText(0, task.name)
            for contrast in task.value:
                contrastItem = QtWidgets.QTreeWidgetItem(taskItem)
                contrastItem.setCheckState(0, QtCore.Qt.Checked)
                contrastItem.setCheckState(0, QtCore.Qt.Unchecked)
                contrastItem.setText(0, contrast.name)
        ######
        MainView.setWindowTitle(_translate("MainView", "MainWindow"))
        self.selectInputFilesLabel.setText(_translate("MainView", "Select R-fMRI data:"))
        self.selectOutputDirLabel.setText(_translate("MainView", "Select output directory:"))
        self.browseInputFilesButton.setText(_translate("MainView", "Browse..."))
        self.browseOutputDirButton.setText(_translate("MainView", "Browse..."))
        self.selectTasksLabel.setText(_translate("MainView", "Select tasks:"))
        self.runPredictButton.setText(_translate("MainView", "Run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.predictView), _translate("MainView", "Predict"))
        self.predictedInputBrowseButton.setText(_translate("MainView", "Browse..."))
        self.predictedInputLabel.setText(_translate("MainView", "Select predicted activation files:"))
        self.analysisCorrelationsRadioButton.setText(_translate("MainView", "Correlations"))
        self.runAnalysisButton.setText(_translate("MainView", "Analyze"))
        self.analysisSignificantRadioButton.setText(_translate("MainView", "Areas of significant activation"))
        self.analysisNameLabel.setText(_translate("MainView", "Insert Analysis session name:"))
        self.actualInputBrowseButton.setText(_translate("MainView", "Browse..."))
        self.actualInputLabel.setText(_translate("MainView", "Add actual activation files to compare:"))
        self.analysisMeanRadioButton.setText(_translate("MainView", "Get mean predicted activation for group"))
        self.comparisonSignificantRadioButton.setText(_translate("MainView", "Areas of significant activation"))
        self.comparisonCorrelationsRadioButton.setText(_translate("MainView", "Correlations"))
        self.runComparisonButton.setText(_translate("MainView", "Compare"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.AnalyzeView), _translate("MainView", "Analyze"))




