# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\Sadna\src\git\PITECA\UI\main-window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 570)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/brain-512.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.MainView = QtWidgets.QTabWidget(Form)
        self.MainView.setGeometry(QtCore.QRect(10, 10, 431, 541))
        self.MainView.setObjectName("MainView")
        self.PredictView = QtWidgets.QWidget()
        self.PredictView.setObjectName("PredictView")
        self.groupBox = QtWidgets.QGroupBox(self.PredictView)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 371, 141))
        self.groupBox.setObjectName("groupBox")
        self.browseInputFilesButton = QtWidgets.QPushButton(self.groupBox)
        self.browseInputFilesButton.setGeometry(QtCore.QRect(280, 60, 75, 23))
        self.browseInputFilesButton.setObjectName("browseInputFilesButton")
        self.inputFilesLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.inputFilesLineEdit.setGeometry(QtCore.QRect(10, 60, 261, 20))
        self.inputFilesLineEdit.setObjectName("inputFilesLineEdit")
        self.selectInputFilesLabel = QtWidgets.QLabel(self.groupBox)
        self.selectInputFilesLabel.setGeometry(QtCore.QRect(10, 30, 151, 16))
        self.selectInputFilesLabel.setObjectName("selectInputFilesLabel")
        self.browseOutputDirButton = QtWidgets.QPushButton(self.groupBox)
        self.browseOutputDirButton.setGeometry(QtCore.QRect(280, 110, 75, 23))
        self.browseOutputDirButton.setObjectName("browseOutputDirButton")
        self.selectOutputDirLabel = QtWidgets.QLabel(self.groupBox)
        self.selectOutputDirLabel.setGeometry(QtCore.QRect(10, 90, 151, 16))
        self.selectOutputDirLabel.setObjectName("selectOutputDirLabel")
        self.outputDirLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.outputDirLineEdit.setGeometry(QtCore.QRect(10, 110, 261, 20))
        self.outputDirLineEdit.setObjectName("outputDirLineEdit")
        self.tasksTree = QtWidgets.QTreeWidget(self.PredictView)
        self.tasksTree.setGeometry(QtCore.QRect(10, 160, 371, 211))
        self.tasksTree.setObjectName("tasksTree")
        self.runPredictButton = QtWidgets.QPushButton(self.PredictView)
        self.runPredictButton.setGeometry(QtCore.QRect(10, 380, 75, 23))
        self.runPredictButton.setAutoDefault(False)
        self.runPredictButton.setDefault(False)
        self.runPredictButton.setFlat(False)
        self.runPredictButton.setObjectName("runPredictButton")
        self.MainView.addTab(self.PredictView, "")
        self.AnalyzeView = QtWidgets.QWidget()
        self.AnalyzeView.setObjectName("AnalyzeView")
        self.selectDomainLabel = QtWidgets.QLabel(self.AnalyzeView)
        self.selectDomainLabel.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.selectDomainLabel.setObjectName("selectDomainLabel")
        self.domainComboBox = QtWidgets.QComboBox(self.AnalyzeView)
        self.domainComboBox.setGeometry(QtCore.QRect(90, 10, 111, 22))
        self.domainComboBox.setObjectName("domainComboBox")
        self.domainComboBox.addItem("")
        self.selectTaskLabel = QtWidgets.QLabel(self.AnalyzeView)
        self.selectTaskLabel.setGeometry(QtCore.QRect(230, 10, 61, 16))
        self.selectTaskLabel.setObjectName("selectTaskLabel")
        self.taskComboBox = QtWidgets.QComboBox(self.AnalyzeView)
        self.taskComboBox.setGeometry(QtCore.QRect(300, 10, 111, 22))
        self.taskComboBox.setObjectName("taskComboBox")
        self.selectPredictedLabel = QtWidgets.QLabel(self.AnalyzeView)
        self.selectPredictedLabel.setGeometry(QtCore.QRect(10, 50, 171, 16))
        self.selectPredictedLabel.setObjectName("selectPredictedLabel")
        self.selectPredictedLineEdit = QtWidgets.QLineEdit(self.AnalyzeView)
        self.selectPredictedLineEdit.setGeometry(QtCore.QRect(10, 70, 321, 20))
        self.selectPredictedLineEdit.setObjectName("selectPredictedLineEdit")
        self.browsePredictedButton = QtWidgets.QPushButton(self.AnalyzeView)
        self.browsePredictedButton.setGeometry(QtCore.QRect(340, 70, 75, 23))
        self.browsePredictedButton.setObjectName("browsePredictedButton")
        self.analysisMeanRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.analysisMeanRadioButton.setGeometry(QtCore.QRect(20, 110, 241, 17))
        self.analysisMeanRadioButton.setObjectName("analysisMeanRadioButton")
        self.analysisCorrelationsRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.analysisCorrelationsRadioButton.setGeometry(QtCore.QRect(20, 140, 82, 17))
        self.analysisCorrelationsRadioButton.setObjectName("analysisCorrelationsRadioButton")
        self.analysisSignificantRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.analysisSignificantRadioButton.setGeometry(QtCore.QRect(20, 170, 211, 17))
        self.analysisSignificantRadioButton.setObjectName("analysisSignificantRadioButton")
        self.browseActualButton = QtWidgets.QPushButton(self.AnalyzeView)
        self.browseActualButton.setGeometry(QtCore.QRect(340, 280, 75, 23))
        self.browseActualButton.setObjectName("browseActualButton")
        self.comparisonCorrelationsRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.comparisonCorrelationsRadioButton.setGeometry(QtCore.QRect(20, 320, 82, 17))
        self.comparisonCorrelationsRadioButton.setObjectName("comparisonCorrelationsRadioButton")
        self.addActualLineEdit = QtWidgets.QLineEdit(self.AnalyzeView)
        self.addActualLineEdit.setGeometry(QtCore.QRect(10, 280, 321, 20))
        self.addActualLineEdit.setObjectName("addActualLineEdit")
        self.comparisonSignificantRadioButton = QtWidgets.QRadioButton(self.AnalyzeView)
        self.comparisonSignificantRadioButton.setGeometry(QtCore.QRect(20, 350, 181, 17))
        self.comparisonSignificantRadioButton.setObjectName("comparisonSignificantRadioButton")
        self.addActualLabel = QtWidgets.QLabel(self.AnalyzeView)
        self.addActualLabel.setGeometry(QtCore.QRect(10, 260, 251, 16))
        self.addActualLabel.setObjectName("addActualLabel")
        self.pushButton_6 = QtWidgets.QPushButton(self.AnalyzeView)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 200, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.AnalyzeView)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 380, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.selectDomainLabel.raise_()
        self.domainComboBox.raise_()
        self.selectTaskLabel.raise_()
        self.taskComboBox.raise_()
        self.selectPredictedLabel.raise_()
        self.selectPredictedLineEdit.raise_()
        self.browsePredictedButton.raise_()
        self.analysisMeanRadioButton.raise_()
        self.analysisCorrelationsRadioButton.raise_()
        self.analysisSignificantRadioButton.raise_()
        self.browseActualButton.raise_()
        self.comparisonCorrelationsRadioButton.raise_()
        self.addActualLineEdit.raise_()
        self.comparisonSignificantRadioButton.raise_()
        self.addActualLabel.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.MainView.addTab(self.AnalyzeView, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(230, 10, 61, 16))
        self.label_16.setObjectName("label_16")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_27.setGeometry(QtCore.QRect(90, 230, 75, 23))
        self.pushButton_27.setObjectName("pushButton_27")
        self.label_17 = QtWidgets.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(10, 50, 171, 16))
        self.label_17.setObjectName("label_17")
        self.listWidget_8 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_8.setGeometry(QtCore.QRect(10, 70, 191, 151))
        self.listWidget_8.setObjectName("listWidget_8")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_8.addItem(item)
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_28.setGeometry(QtCore.QRect(10, 230, 75, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_7.setGeometry(QtCore.QRect(90, 10, 111, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_18.setObjectName("label_18")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_8.setGeometry(QtCore.QRect(300, 10, 111, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.listWidget_3 = QtWidgets.QListWidget(self.tab_2)
        self.listWidget_3.setGeometry(QtCore.QRect(220, 70, 191, 151))
        self.listWidget_3.setObjectName("listWidget_3")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_3.addItem(item)
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_29.setGeometry(QtCore.QRect(220, 230, 75, 23))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_30.setGeometry(QtCore.QRect(300, 230, 75, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(220, 50, 171, 16))
        self.label_19.setObjectName("label_19")
        self.toolBox_2 = QtWidgets.QToolBox(self.tab_2)
        self.toolBox_2.setEnabled(True)
        self.toolBox_2.setGeometry(QtCore.QRect(10, 270, 401, 201))
        self.toolBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_4.setObjectName("page_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.page_4)
        self.checkBox_5.setGeometry(QtCore.QRect(30, 10, 91, 17))
        self.checkBox_5.setObjectName("checkBox_5")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_4)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 80, 75, 23))
        self.pushButton_12.setAutoDefault(False)
        self.pushButton_12.setDefault(False)
        self.pushButton_12.setFlat(False)
        self.pushButton_12.setObjectName("pushButton_12")
        self.toolBox_2.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page_5.setObjectName("page_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.page_5)
        self.checkBox_6.setGeometry(QtCore.QRect(30, 10, 91, 17))
        self.checkBox_6.setObjectName("checkBox_6")
        self.pushButton_26 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_26.setGeometry(QtCore.QRect(30, 80, 75, 23))
        self.pushButton_26.setAutoDefault(False)
        self.pushButton_26.setDefault(False)
        self.pushButton_26.setFlat(False)
        self.pushButton_26.setObjectName("pushButton_26")
        self.toolBox_2.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 401, 120))
        self.page_6.setObjectName("page_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.page_6)
        self.checkBox_7.setGeometry(QtCore.QRect(30, 10, 241, 17))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.page_6)
        self.checkBox_8.setGeometry(QtCore.QRect(30, 30, 211, 17))
        self.checkBox_8.setObjectName("checkBox_8")
        self.pushButton_31 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_31.setGeometry(QtCore.QRect(30, 80, 75, 23))
        self.pushButton_31.setAutoDefault(False)
        self.pushButton_31.setDefault(False)
        self.pushButton_31.setFlat(False)
        self.pushButton_31.setObjectName("pushButton_31")
        self.toolBox_2.addItem(self.page_6, "")
        self.MainView.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 371, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 40, 241, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(20, 20, 211, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 70, 191, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(290, 40, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 130, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.MainView.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.MainView.setCurrentIndex(1)
        self.toolBox_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PITECA"))
        self.groupBox.setTitle(_translate("Form", "Select Paths"))
        self.browseInputFilesButton.setText(_translate("Form", "Browse..."))
        self.selectInputFilesLabel.setText(_translate("Form", "Select Input files:"))
        self.browseOutputDirButton.setText(_translate("Form", "Browse..."))
        self.selectOutputDirLabel.setText(_translate("Form", "Select Output folder:"))
        self.runPredictButton.setText(_translate("Form", "Run"))
        self.MainView.setTabText(self.MainView.indexOf(self.PredictView), _translate("Form", "Predict"))
        self.selectDomainLabel.setText(_translate("Form", "Select Domain:"))
        self.domainComboBox.setItemText(0, _translate("Form", "haha"))
        self.selectTaskLabel.setText(_translate("Form", "Select Task:"))
        self.selectPredictedLabel.setText(_translate("Form", "Select predicted activation files:"))
        self.browsePredictedButton.setText(_translate("Form", "Browse..."))
        self.analysisMeanRadioButton.setText(_translate("Form", "Get mean predicted activation for group"))
        self.analysisCorrelationsRadioButton.setText(_translate("Form", "Correlations"))
        self.analysisSignificantRadioButton.setText(_translate("Form", "Areas of significant activation"))
        self.browseActualButton.setText(_translate("Form", "Browse..."))
        self.comparisonCorrelationsRadioButton.setText(_translate("Form", "Correlations"))
        self.comparisonSignificantRadioButton.setText(_translate("Form", "Areas of significant activation"))
        self.addActualLabel.setText(_translate("Form", "Add actual activation files to compare:"))
        self.pushButton_6.setText(_translate("Form", "Analyze"))
        self.pushButton_7.setText(_translate("Form", "Compare"))
        self.MainView.setTabText(self.MainView.indexOf(self.AnalyzeView), _translate("Form", "Analyze Results"))
        self.label_16.setText(_translate("Form", "Select Task:"))
        self.pushButton_27.setText(_translate("Form", "Remove"))
        self.label_17.setText(_translate("Form", "Add predicted activation files:"))
        __sortingEnabled = self.listWidget_8.isSortingEnabled()
        self.listWidget_8.setSortingEnabled(False)
        item = self.listWidget_8.item(0)
        item.setText(_translate("Form", "31122_pred.dscalar.nii"))
        item = self.listWidget_8.item(1)
        item.setText(_translate("Form", "45566_pred.dscalar.nii"))
        item = self.listWidget_8.item(2)
        item.setText(_translate("Form", "78899_pred.dscalar.nii"))
        self.listWidget_8.setSortingEnabled(__sortingEnabled)
        self.pushButton_28.setText(_translate("Form", "Add..."))
        self.comboBox_7.setItemText(0, _translate("Form", "EMOTION"))
        self.comboBox_7.setItemText(1, _translate("Form", "GAMBLING"))
        self.comboBox_7.setItemText(2, _translate("Form", "LANGUAGE"))
        self.comboBox_7.setItemText(3, _translate("Form", "MOTOR"))
        self.comboBox_7.setItemText(4, _translate("Form", "RELATIONAL"))
        self.comboBox_7.setItemText(5, _translate("Form", "SOCIAL"))
        self.comboBox_7.setItemText(6, _translate("Form", "WM"))
        self.label_18.setText(_translate("Form", "Select Domain:"))
        self.comboBox_8.setItemText(0, _translate("Form", "FACES"))
        self.comboBox_8.setItemText(1, _translate("Form", "SHAPES"))
        self.comboBox_8.setItemText(2, _translate("Form", "FACES-SHAPES"))
        __sortingEnabled = self.listWidget_3.isSortingEnabled()
        self.listWidget_3.setSortingEnabled(False)
        item = self.listWidget_3.item(0)
        item.setText(_translate("Form", "31122_act.dscalar.nii"))
        item = self.listWidget_3.item(1)
        item.setText(_translate("Form", "45566_act.dscalar.nii"))
        item = self.listWidget_3.item(2)
        item.setText(_translate("Form", "78899_act.dscalar.nii"))
        self.listWidget_3.setSortingEnabled(__sortingEnabled)
        self.pushButton_29.setText(_translate("Form", "Add..."))
        self.pushButton_30.setText(_translate("Form", "Remove"))
        self.label_19.setText(_translate("Form", "Add actual activation files:"))
        self.checkBox_5.setText(_translate("Form", "Save Nifti files"))
        self.pushButton_12.setText(_translate("Form", "Run"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_4), _translate("Form", "Create overlap maps for predicted+actual activations"))
        self.checkBox_6.setText(_translate("Form", "Save Nifti files"))
        self.pushButton_26.setText(_translate("Form", "Run"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), _translate("Form", "Pairwise overlap analysis with DICE index"))
        self.checkBox_7.setText(_translate("Form", "Include correlation with mean of predictions"))
        self.checkBox_8.setText(_translate("Form", "Include correlation with canonical brain"))
        self.pushButton_31.setText(_translate("Form", "Run"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("Form", "Pairwise correlation analysis using R"))
        self.MainView.setTabText(self.MainView.indexOf(self.tab_2), _translate("Form", "Compare"))
        self.groupBox_3.setTitle(_translate("Form", "Features"))
        self.lineEdit_3.setText(_translate("Form", "PATICA/Fetures"))
        self.radioButton.setText(_translate("Form", "Save features in:"))
        self.radioButton_2.setText(_translate("Form", "Don\'t save features."))
        self.pushButton_11.setText(_translate("Form", "Browse..."))
        self.pushButton.setText(_translate("Form", "Apply"))
        self.MainView.setTabText(self.MainView.indexOf(self.tab_3), _translate("Form", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

